### ISSUE TITLE
gtest 1.8.0 is old

### ISSUE THREAD

**Issue by hobu** [connormanning/entwine#233]
This no longer compiles with newer MSVC. Please update gtest to 1.10.0 or better.

**Comment by defaultbranch** [comment]
@hobu 

- I think this ticked is outdated for the `master` branch, today that already ships `googletest-release-1.10.0`
- _but_ today on some Linux, GCC 11.2.1 rejected that version of googletest,

```
In file included from /entwine/test/googletest-release-1.10.0/googletest/src/gtest-all.cc:42:
/entwine/test/googletest-release-1.10.0/googletest/src/gtest-death-test.cc: In function 'bool testing::internal::StackGrowsDown()':
/entwine/test/googletest-release-1.10.0/googletest/src/gtest-death-test.cc:1301:24: error: 'dummy' may be used uninitialized [-Werror=maybe-uninitialized]
 1301 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
```

- _and_ I also think that (these days) it is bad practice to copy upstream library code into a project, because this makes it hard or impossible to track/keep up to date with upstream changes
  - did you consider to pull in googletest either as a git submodule, or as some cmake dependency?

**Comment by connormanning** [comment]
This has been done, gtest is now updated to v1.13.0.
